services:
  laravelapp:
    container_name: laravelapp
    build: .
    ports:
      - "8003:8003"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    restart: always
volumes:
  pgdata:
    driver: local

