services:
  laravelapp:
    container_name: laravelapp
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/var/www/html
    restart: always  # Reinício automático

  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always  # Reinício automático

volumes:
  pgdata:
    driver: local

