name: "Deploy"
on:
  push:
    branches:
      - main
jobs:
  build_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Baixar o código"
        uses: actions/checkout@v4
      - name: "PHP Composer install"
        run:  composer install --no-interaction --no-progress --no-suggest --no-dev --ignore-platform-reqs
        
      - name: "Copiar arquivos para VPS"
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USER }}"
          password: "${{ secrets.SSH_PASS }}"
          source: "."
          target: /home/projetos/devandcoffee/api-auth

      - name: "Build da aplicação"
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "${{ secrets.SSH_HOST }}"
          username: "${{ secrets.SSH_USER }}"
          password: ${{ secrets.SSH_PASS }}
          script: |
            cd /home/projetos/devandcoffee/api-auth
            ./vendor/bin/sail down
            ./vendor/bin/sail up -d
            chmod -R 777 storage bootstrap/cache
